test change pytest ci

diff --git a/.github/workflows/pytest_flow.yaml b/.github/workflows/pytest_flow.yaml
--- a/.github/workflows/pytest_flow.yaml
+++ b/.github/workflows/pytest_flow.yaml
@@ -15,6 +15,9 @@ jobs:
         name: |
             Pytest workflow - Python: ${{ matrix.python-version }}
         runs-on: ubuntu-latest
+        concurrency:
+          group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+          cancel-in-progress: true
         strategy:
             fail-fast: false
             matrix:
@@ -40,14 +43,30 @@ jobs:
             - name: Install dependencies
               run: poetry install --no-interaction --no-ansi
 
-            - name: pytest
+            - name: Run pytest
+              id: pytest
               run: |
                   set -o pipefail
-                  poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=dbt_opiner tests/ --numprocesses 10 | tee pytest-coverage.txt
+                  poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=dbt_opiner --numprocesses 10 tests/ | tee pytest-coverage.txt
+                  if grep -q 'FAILED' pytest-coverage.txt; then
+                    failed_tests_output="$(grep -o 'FAILED .*' pytest-coverage.txt)"
+                    echo "failed_tests=$failed_tests_output" >> $GITHUB_OUTPUT
+                    exit 1
+                  fi
+
+            - name: Post PR comment for failed tests
+              if: failure()
+              uses: mshick/add-pr-comment@v2
+              with:
+                  message: |
+                    :x: Some tests have failed in the `Pytest` workflow:
+                    ```
+                    ${{ steps.pytest.outputs.failed_tests }}
+                    ```
 
             - name: Pytest coverage comment
-              uses: MishaKav/pytest-coverage-comment@main
               if: always()
+              uses: MishaKav/pytest-coverage-comment@main
               with:
                   pytest-coverage-path: ./pytest-coverage.txt
                   title: Coverage Report
